.github/PULL_REQUEST_TEMPLATE
pom.xml

Add pull request template.
Make every pr has clear description and reason and can accelerate review.
No
Only a template file, no need to test.

Add pull request template

---

client-spark/common/pom.xml
client-spark/spark2/pom.xml
client-spark/spark3/pom.xml
client/pom.xml
common/pom.xml
coordinator/pom.xml
integration-test/common/pom.xml
integration-test/spark-common/pom.xml
integration-test/spark3/pom.xml
internal-client/pom.xml
pom.xml
proto/pom.xml
server/pom.xml
storage/pom.xml

Upgrade master branch's version to 0.2.0-SNAPSHOT
We have released 0.1.0 so upgrade the master branch version.
No
No need.

Upgrade version to 0.2.0-SNAPSHOT

---

integration-test/common/pom.xml
integration-test/spark3/pom.xml
pom.xml

Fix github dependabot alerts
Dependabot alerts should be fixed
No
UT and integration test

Fix Dependabot alerts

---

checkstyle.xml
client-spark/common/src/main/java/org/apache/spark/shuffle/RssShuffleUtils.java
client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
common/src/main/java/com/tencent/rss/common/ShuffleAssignmentsInfo.java
common/src/main/java/com/tencent/rss/common/util/ExitUtils.java
common/src/main/java/com/tencent/rss/common/web/JettyServer.java
coordinator/src/main/java/com/tencent/rss/coordinator/AssignmentStrategy.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorServer.java
internal-client/src/main/java/com/tencent/rss/client/impl/grpc/CoordinatorGrpcClient.java
storage/src/main/java/com/tencent/rss/storage/handler/impl/AbstractHdfsClientReadHandler.java
storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsClientReadHandler.java
storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsFileWriter.java

Add modifier, comment and import checking into checkstyle,
- ModifierOrder
- CommentsIndentation
- UnusedImports
- RedundantImport
- RedundantModifier
Enhance checkstyle
No
Normal ut and integration test

[Feature] Add modifier, comment and import checking into checkstyle

---

common/src/main/java/com/tencent/rss/common/config/RssBaseConf.java
common/src/main/java/com/tencent/rss/common/metrics/GRPCMetrics.java
common/src/main/java/com/tencent/rss/common/rpc/GrpcServer.java
common/src/main/java/com/tencent/rss/common/rpc/MonitoringServerCall.java
common/src/main/java/com/tencent/rss/common/rpc/MonitoringServerCallListener.java
common/src/main/java/com/tencent/rss/common/rpc/MonitoringServerInterceptor.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorFactory.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorGrpcMetrics.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorServer.java
coordinator/src/test/java/com/tencent/rss/coordinator/CoordinatorMetricsTest.java
integration-test/common/src/test/java/com/tencent/rss/test/CoordinatorGrpcTest.java
integration-test/common/src/test/java/com/tencent/rss/test/ShuffleServerGrpcTest.java
server/src/main/java/com/tencent/rss/server/ShuffleServer.java
server/src/main/java/com/tencent/rss/server/ShuffleServerFactory.java
server/src/main/java/com/tencent/rss/server/ShuffleServerGrpcMetrics.java
server/src/main/java/com/tencent/rss/server/ShuffleServerGrpcService.java
server/src/main/java/com/tencent/rss/server/ShuffleServerMetrics.java
server/src/test/java/com/tencent/rss/server/ShuffleServerMetricsTest.java

The PR is target to add metrics to collect connection info of grpc, include: current activity connection, total connection
Add Interceptor, Listener, Call of grpc
No
UT added

Add metrics to collect connection info of grpc

---

integration-test/common/src/test/java/com/tencent/rss/test/HealthCheckCoordinatorGrpcTest.java

Fix the flaky test.
Flaky test will cause ga fail sometimes.
No
No, test only.

[Improvement] Fix the flaky test

---

pom.xml

Upgrade org.apache.logging.log4j:log4j-core to version 2.15.0.
Fix log4j-core dependabot
No
Normal ut and integration test

Fix log4j-core dependabot

---

integration-test/common/src/test/java/com/tencent/rss/test/IntegrationTestBase.java

Remove the useless code that creat an extra coordinator server
These codes are useless and kind of hardcode.
No
ut and integration test

[Improvement]Remove useless code in test base

---

README.md

Update Readme with memory shuffle support
Update guide with latest implementation
No
not necessary

Update Readme with memory shuffle support

---

client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
coordinator/src/test/java/com/tencent/rss/coordinator/PartitionBalanceAssignmentStrategyTest.java
server/src/main/java/com/tencent/rss/server/HealthCheck.java

Fix time unit from micro to mill
bug fix
No
exist UT

Fix time unit from micro to mill

---

.github/workflows/maven.yml

Add upload command in workflows
The current CI cannot review log.
No
run github CI

upload unit test log in github CI

---

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
integration-test/spark-common/src/test/java/com/tencent/rss/test/RepartitionTest.java

Fix memory leak problem in Spark executor
Bug fix
No
update exist Test case

[Bug]Fix memory leak in spark executor

---

server/src/main/java/com/tencent/rss/server/ShuffleServerMetrics.java
server/src/main/java/com/tencent/rss/server/storage/HdfsStorageManager.java
server/src/main/java/com/tencent/rss/server/storage/LocalStorageManager.java
server/src/test/java/com/tencent/rss/server/ShuffleServerMetricsTest.java

Add some metrics that count the data size of localfile and hdfs.
Improve the observability。
No
Manually.

[Feature] Add the data size of metrics HDFS and LOCALFILE

---

client-spark/common/pom.xml
client-spark/spark2/pom.xml
client-spark/spark3/pom.xml
client/pom.xml
common/pom.xml
coordinator/pom.xml
integration-test/common/pom.xml
integration-test/spark-common/pom.xml
integration-test/spark3/pom.xml
internal-client/pom.xml
pom.xml
proto/pom.xml
server/pom.xml
storage/pom.xml

Update version to 0.2.0
For new release 0.2.0
No
Not necessary

Update version to 0.2.0

---

README.md

Update readme for new configuration
Update readme according to latest version
No
not necessary

[Doc] Update readme for new configuration

---

client-spark/common/src/main/java/org/apache/spark/shuffle/RssClientConfig.java

Update some default values of parameters.
Avoid to involve extra  parameters in the Spark submitter.
No. 
All existing UTs.

[Improvement] Update some default values of parameters

---

coordinator/src/main/java/com/tencent/rss/coordinator/AccessCandidatesChecker.java
coordinator/src/main/java/com/tencent/rss/coordinator/AccessClusterLoadChecker.java
coordinator/src/main/java/com/tencent/rss/coordinator/AccessManager.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorMetrics.java
coordinator/src/test/java/com/tencent/rss/coordinator/AccessClusterLoadCheckerTest.java
coordinator/src/test/java/com/tencent/rss/coordinator/CoordinatorMetricsTest.java
integration-test/common/src/test/java/com/tencent/rss/test/AccessCandidatesCheckerHdfsTest.java

1 add metric to count the cluster total access request count
2 add metric to count the denied access request by candidates checker
3 add metric to count the denied access request by load checker
Help to observe the status of the cluster
No
UT and system test

[Feature] add access related metrics

---

README.md
client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
integration-test/spark-common/src/test/java/com/tencent/rss/test/SparkIntegrationTestBase.java
integration-test/spark3/pom.xml
pom.xml

Support Spark 3.2
We need support more Spark Versions
No
GA passed （include profiles spark2,spark3,spark3.0,spark3.1,spark3.2）

[Feature] Support Spark 3.2

---

client-spark/common/pom.xml
client-spark/spark2/pom.xml
client-spark/spark3/pom.xml
client/pom.xml
common/pom.xml
coordinator/pom.xml
integration-test/common/pom.xml
integration-test/spark-common/pom.xml
integration-test/spark3/pom.xml
internal-client/pom.xml
pom.xml
proto/pom.xml
server/pom.xml
storage/pom.xml

upgrade version number
release 0.3.0
no
no

upgrade to 0.3.0

---

client-spark/common/pom.xml
client-spark/spark2/pom.xml
client-spark/spark3/pom.xml
client/pom.xml
common/pom.xml
coordinator/pom.xml
integration-test/common/pom.xml
integration-test/spark-common/pom.xml
integration-test/spark3/pom.xml
internal-client/pom.xml
pom.xml
proto/pom.xml
server/pom.xml
storage/pom.xml

upgrade version number
release 0.4.0
no
no

upgrade to 0.4.0

---

client/src/main/java/com/tencent/rss/client/impl/ShuffleWriteClientImpl.java
integration-test/common/src/test/java/com/tencent/rss/test/QuorumTest.java

Fix a bug of report quorum.
Without this patch, report quorum will fail when server number is more than replica.
No.
Update UTs to start more servers.

[Bugfix] Fix quorum bug in blockIds report

---

client-mr/pom.xml
client-spark/common/pom.xml
client-spark/spark2/pom.xml
client-spark/spark3/pom.xml
client/pom.xml
common/pom.xml
coordinator/pom.xml
integration-test/common/pom.xml
integration-test/mr/pom.xml
integration-test/spark-common/pom.xml
integration-test/spark3/pom.xml
internal-client/pom.xml
pom.xml
proto/pom.xml
server/pom.xml
storage/pom.xml

upgrade version number
upgrade to 0.5.0-snapshot
no
no

upgrade to 0.5.0-snapshot

---

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java

Sometimes bufferManager will be removed in another thread, so it will throw npe.
Avoid npe problems.
No
No, just add some checkers.

[Bug] Fix NPE problems occasionally

---

coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorServer.java

duplicate servlets map in Coordinator Server
fix https://github.com/Tencent/Firestorm/issues/122
no
Manual

remove duplicate servlets map

---

build_distribution.sh

Add build command for mr profile in the build distribution script.
We also need mr client jar in our distribution package.
No
Manual test

[Improvement] Add build script for mr profile

---

client-mr/pom.xml
common/pom.xml

Remove unused dependency and remove the version in the children pom file.
Optmize project dependency
No
GA passed.

[Minor] Optimize maven dependency

---

coordinator/src/main/java/com/tencent/rss/coordinator/ApplicationManager.java
coordinator/src/test/java/com/tencent/rss/coordinator/ApplicationManagerTest.java

There has NPE problem if there has no remote storage
Bug fix
No
New UT is added

[Bug] Fix NPE problem in coordinator if there has no remote storage

---

common/src/main/java/com/tencent/rss/common/util/RssUtils.java
common/src/test/java/com/tencent/rss/common/util/RssUtilsTest.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorMetrics.java
server/src/main/java/com/tencent/rss/server/ShuffleServerMetrics.java
server/src/test/java/com/tencent/rss/server/ShuffleFlushManagerTest.java
server/src/test/java/com/tencent/rss/server/ShuffleServerMetricsTest.java

As metric name, host name has invalid character like `-`, `.`
Replace them with `_` to generate valid metric name
Bug fix
No
UT added

[Bug] Update hostname to valid metric name

---

client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
client-mr/src/test/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMasterTest.java

After we modify the configuration, we should update the hdfs file and the local file. And we don't support recovery now, so we close it.
If we don't have this patch,  we cannot use new configuration.
No
Manual test and new UT

[Bugfix] AppMaster configuration doesn't work

---

client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java

If there is no shuffle, we shouldn't acess rss, otherwise we will encounter an error
If a application has no shuffle, it will occur a error
No
Manual test

[Bugfix] If there is no shuffle, we shouldn't acess rss

---

server/src/main/java/com/tencent/rss/server/ShuffleUploader.java

Fix integer division in floating-point context.
Fix precision loss and potential overflow.
No.
https://github.com/kaijchen/Firestorm/actions/runs/2384201966

[Minor] Fix integer division in floating-point context

---

README.md

Update doc to configure MapReduce client.
The previous version only has Spark configuration.
No.
No, just doc.

[Improvement] Update doc to configure MapReduce client

---

.github/workflows/build.yml
.github/workflows/parallel.yml
.github/workflows/sequential.yml

1. Add more spark profiles in CI
* spark2.3
* spark3.0
* spark3.2 
To ensure changes won't break any versions.
No.
See CI.

[Improvement] Add more spark profiles in CI

---

client-mr/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java
client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java
client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java
client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssShuffle.java

We don't use RssConfig to override JobConf, Because some configuration will be overrided by default configuration. User configuration don't take effect.
#163 introduced this problem. If we don't have this patch, some configuration will not take effect, like `io.sort.mb`.
No
Manual test

[Bugfix] Fix MR configuration problems

---

client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssFetcher.java

Fix MR ui reduce's transferRate
Without this patch, the  reduce's transferRate is incorrect on web UI.
No.
By hand.

[Bigfix] Fix MR web ui reduce's transferRate

---

client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssBypassWriter.java

Add extra checkout to avoid write data to MR's OnDiskMapOutput. 
RSS leverages its own compression, it is incompatible with Hadoop's disk file compression.
So we should disable this situation.
Just new throw.
No.

[Improvement] Add extra check to avoid write data to MR's OnDiskMapOutput

---

internal-client/src/main/java/com/tencent/rss/client/impl/grpc/ShuffleServerGrpcClient.java

Minor fix. Just to remove the unnecessary data structures
Clean code
No
No

Remove the unnecessary data structures

---

integration-test/common/src/test/java/com/tencent/rss/test/ShuffleServerGrpcTest.java

Disable flaky test
The test is not important, but it's very flaky. We disable this test temporarily. We will fix this flaky test later.
No
No need.

[Improvement] Disable flaky test

---

README.md

Update Readme for latest features, eg, multiple remote storage support, dynamic client conf etc.
Doc should be updated
No
No need

[Doc] Update readme with features like multiple remote storage support

---

coordinator/src/main/java/com/tencent/rss/coordinator/ServerNode.java
coordinator/src/main/java/com/tencent/rss/coordinator/SimpleClusterManager.java
coordinator/src/test/java/com/tencent/rss/coordinator/SimpleClusterManagerTest.java

Remove serverNode from tags structure when heartbeart timeout
Remove serverNode from tags structure when heartbeart timeout
No
UT

[Minor] Remove serverNode from tags structure when heartbeart timeout

---

coordinator/src/main/java/com/tencent/rss/coordinator/ClusterManager.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorServer.java
coordinator/src/main/java/com/tencent/rss/coordinator/SimpleClusterManager.java
coordinator/src/test/java/com/tencent/rss/coordinator/BasicAssignmentStrategyTest.java
coordinator/src/test/java/com/tencent/rss/coordinator/PartitionBalanceAssignmentStrategyTest.java
coordinator/src/test/java/com/tencent/rss/coordinator/SimpleClusterManagerTest.java
integration-test/common/src/test/java/com/tencent/rss/test/CoordinatorGrpcTest.java

1. Change the method of shutdown to close
2. Close resources of clustermanager in test cases
Close resources to reduce the resource occupying in test cases.
No.
Test cases

[MINOR] Close clusterManager resources

---

client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java

Close coordinatorClients when DelegationRssShuffleManager stops.
The coordinatorClients in DelegationRssShuffleManager are never closed.
No
No

Close coordinatorClients when DelegationRssShuffleManager stops

---

server/src/main/java/com/tencent/rss/server/ShuffleFlushManager.java
server/src/main/java/com/tencent/rss/server/ShuffleTaskManager.java

Make clearResourceThread daemon and processEventThread daemon.
`clearResourceThread` and `processEventThread` never exits, we can make it daemon.
No
No

Make clearResourceThread and processEventThread daemon

---

coordinator/src/main/java/com/tencent/rss/coordinator/ClusterManagerFactory.java
coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorServer.java
coordinator/src/main/java/com/tencent/rss/coordinator/SimpleClusterManager.java
coordinator/src/test/java/com/tencent/rss/coordinator/BasicAssignmentStrategyTest.java
coordinator/src/test/java/com/tencent/rss/coordinator/PartitionBalanceAssignmentStrategyTest.java
coordinator/src/test/java/com/tencent/rss/coordinator/SimpleClusterManagerTest.java

Support using remote fs path to specify the excludeNodesFilePath
When existing two coordinators serving for online, we hope they can read the consistent exclude nodes file insteading of using the localfile syncing manually.
Yes. It's an incompatible change. 
When the default fs is HDFS in the core-site.xml, and the excludeFilePath is specified to "/user/xxxxx" in coordinator server.
After applied this patch, filesystem will be initialized to remote HDFS due to lacking scheme.
Unit tests.

Support using remote fs path to specify the excludeNodesFilePath

---

conf/coordinator.conf
conf/server.conf

I modify the file `conf/server.conf` and `conf/coordinator.conf`. Some configurations are not recommended. I modify them
Give users a better configuration template
No
No need.

[Improvement] Modify configuration template
