Tencent/Firestorm

integration-test/common/src/test/java/com/tencent/rss/test/MultiStorageFaultToleranceTest.java, integration-test/common/src/test/java/com/tencent/rss/test/MultiStorageTest.java, server/src/main/java/com/tencent/rss/server/MultiStorageManager.java, server/src/main/java/com/tencent/rss/server/ShuffleServerConf.java, server/src/main/java/com/tencent/rss/server/ShuffleUploader.java, server/src/test/java/com/tencent/rss/server/ShuffleUploaderTest.java, storage/src/main/java/com/tencent/rss/storage/common/DiskItem.java
- Limit upload segment num to upload thread num in force mode
- Add hard upload time restriction in force mode
A huge shuffle exhaust all the disk capacity and it will trigger force upload in multistorage mode, which it is upload according to the shuffle granularity. But the huge shuffle may have lots of segments much larger than the upload thread number and make the upload time longer than the event flush expire threshold. Therefore we need to restrict both the segment number of a single shuffle and the upload time in force mode. 
No
UT, integration test and terasort.
=> [Feature] Limit upload segment num and upload time in force mode

storage/src/main/java/com/tencent/rss/storage/api/ShuffleReader.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/AbstractHdfsClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsFileReader.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsShuffleWriteHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/LocalFileReader.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/MultiStorageHdfsClientReadHandler.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/HdfsClientReadHandlerTest.java
1. Add read shuffle index api in hdfs read handler
2. Read all index data from hdfs
3. Use offset and length to read data from hdfs
As mentioned in #6, we want to read index first and use it to read data and
then we could realize server HA and read replica on demand.
No
UT, integration test, TPC-DS and terasort.
=> [Feature] Read index file first in hdfs mode

integration-test/common/src/test/java/com/tencent/rss/test/MultiStorageTest.java, server/src/main/java/com/tencent/rss/server/ShuffleFlushManager.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/LocalFileWriteHandler.java
When event write data in LocalFileWriteHanlder, if base directorys don't exist,  the method will return directly, not throw FileNotFoundException.
In multiStorage mode, shuffle will be started upload after shuffle is read. When shuffle has been uploaded totally,  shuffle directory will be deleted. Speculative tasks may also write its data to shuffle server.So these data will cause FileNotFoundExceptions, these exceptions will degrade performance.
No.
Add newly UTS.
=> [Improvement] Avoid speculative tasks causing writing errors after shuffle is uploaded and deleted

pom.xml
Upgrade org.apache.logging.log4j:log4j-core to version 2.16.0.
Fix log4j-core dependabot
>The fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was incomplete in certain non-default configurations. This could allow attackers with control over Thread Context Map (MDC) input data when the logging configuration uses a non-default Pattern Layout with either a Context Lookup (for example, $${ctx:loginId}) or a Thread Context Map pattern (%X, %mdc, or %MDC) to craft malicious input data using a JNDI Lookup pattern resulting in a denial of service (DOS) attack.
No
Normal ut and integration test
=> [Improvement] fix log4j Dependabot alerts

integration-test/common/src/test/java/com/tencent/rss/test/HealthCheckCoordinatorGrpcTest.java
Increase timeout setting (3 -> 5)
Fix flaky testes in HealthCheckCoordinatorGrpcTest
No
UT
=> [MINOR] Fix flaky testes in HealthCheckCoordinatorGrpcTest

client-spark/common/src/main/java/org/apache/spark/shuffle/RssShuffleUtils.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, integration-test/spark3/src/test/java/com/tencent/rss/test/AQERepartitionTest.java, pom.xml
1. Change some interfaces in the form that Spark2.3 and Spark3.0 support.
2. Add getReaderImpl to unify the different versions of shuffle reader.
Some interfaces are different in Spark2.3 and Spark3.0.
No.
UT & IT with -Pspark2.3 (or -Pspark3.0)
=> [Improvement] Support Firestorm with Spark 2.3 & 3.0

client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java
shut down non daemon executor service created in sendCommit by RssShuffleWriter
non daemon thread will block jvm destroy, which will lead to hang after spark job finished
No
run simple spark job in local mode with RSS, for example:
`./bin/run-example --master local GroupByTest 10 50000 4000`
before this patch, the command will never exist until we interrupt it
after this patch, normal exist after spark job finished
=> Shutdown non-daemon executor service to avoid hang when jvm destroy

client-spark/common/src/main/java/org/apache/spark/shuffle/RssClientConfig.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client/src/main/java/com/tencent/rss/client/util/ClientUtils.java, client/src/test/java/com/tencent/rss/client/ClientUtilsTest.java
Currently, bitmap for saving blockIds exists in multiple shuffle server. The logic to calculate bitmap split number is not necessary any more, remove it to simplify the workflow.
Simplify the workflow
No
exist UTs
=> [Improvement] Remove unnecssary logic to calculate bitmap split number

.github/workflows/maven.yml, client-spark/common/src/test/java/org/apache/spark/shuffle/RssShuffleUtilsTest.java
Update CI workflow to upload logs after failures.
CI does not upload logs after failures.
No.
Add error cases in UT.
=> [Build] Only upload logs when test cases are failed

pom.xml
Upgrade log4j from 2.17.0 to 2.17.1
log4j is unsafe again due to CVE-2021-44832.
Apache Log4j2 versions 2.0-beta7 through 2.17.0 (excluding security fix releases 2.3.2 and 2.12.4) are vulnerable to an attack where an attacker with permission to modify the logging configuration file can construct a malicious configuration using a JDBC Appender with a data source referencing a JNDI URI which can execute remote code. This issue is fixed by limiting JNDI data source names to the java protocol in Log4j2 versions 2.17.1, 2.12.4, and 2.3.2.
No.
Run CI.
=> Fix log4j-core dependabot, upgrade to 2.17.1

client-spark/common/src/main/java/org/apache/spark/shuffle/RssShuffleUtils.java, client-spark/common/src/main/java/org/apache/spark/shuffle/reader/RssShuffleDataIterator.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client-spark/spark2/src/test/java/org/apache/spark/shuffle/writer/RssShuffleWriterTest.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, client/src/main/java/com/tencent/rss/client/impl/ShuffleReadClientImpl.java, client/src/test/java/com/tencent/rss/client/TestUtils.java
To reduce memory cost in Spark executor, the following improvements are included:
1. when shuffle read, don't copy byte[] for every block
2. when shuffle write, metadata should be cleared
To reduce memory and get better performance
No
Update exist UT
=> [Improvement] Reduce memory cost in spark executor

common/src/main/java/com/tencent/rss/common/util/RssUtils.java, common/src/test/java/com/tencent/rss/common/util/RssUtilsTest.java
When we encounter the incomplete index, we just stop reading, not throw an exception.
When we use the storageType MEMORY_HDFS, MEMORY_LOCALFILE_HDFS, after we read data from memory, the data may be flushed to HDFS. So we could read incomplete index data.
No
New ut
=> [Bug] Support to read incomplete index data

client/src/test/java/com/tencent/rss/client/impl/ShuffleReadClientImplTest.java, integration-test/common/src/test/java/com/tencent/rss/test/MultiStorageTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleServerWithMemLocalHdfsTest.java, server/src/test/java/com/tencent/rss/server/ShuffleFlushManagerTest.java, server/src/test/java/com/tencent/rss/server/ShuffleTaskManagerTest.java, storage/src/main/java/com/tencent/rss/storage/factory/ShuffleHandlerFactory.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/ComposedClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsShuffleReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/UploadedHdfsClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/UploadedStorageHdfsShuffleReadHandler.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/HdfsClientReadHandlerTest.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/HdfsHandlerTest.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/HdfsShuffleReadHandlerTest.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/MultiStorageHdfsClientReadHandlerTest.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/MultiStorageHdfsShuffleReadHandlerTest.java
Refactor HdfsClientReadHandler/UploadedHdfsClientReadHandler based on DataSkippableReadHandler
This is "[Feature] Support to skip unexpected and processed segments in LocalFileReadClient (#55)" 's follow-up pull request, we implement the segment filter based on DataSkippableReadHandler.
In this PR, we extends to HdfsClientReadHandler/UploadedHdfsClientReadHandler. 
No.
Run all existing UT & IT.
=> [Follow Up] Support to skip unexpected and processed segments in HDFS

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
We exchange the position between `startHeartbeat` and `registerShuffleServers`
Some register operation will be blocked for long time sometimes. Shuffle server will remove app because of heartbeat timeout.
No
GA passed.
=> [Bug] Exchange the position between `startHeartbeat` and `registerShuffleServers`

client/src/main/java/com/tencent/rss/client/impl/ShuffleReadClientImpl.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleServerWithMemLocalHdfsTest.java, storage/src/main/java/com/tencent/rss/storage/handler/api/ClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/AbstractClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/ComposedClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/HdfsClientReadHandler.java, storage/src/main/java/com/tencent/rss/storage/handler/impl/LocalFileQuorumClientReadHandler.java
Enable to report how many blocks and bytes are read by the client.
1. Add two APIs in the interface of ClientReadHandler
a. void feedbackConsumedBlock(BufferSegment bs);
b. void reportConsumedBlockInfo();
2. Implements the two APIs in ComposedClientReadHandler.
Without this patch, the client side is difficult to debug.
No.
Add a new UT.
=> [Improvement] Add detailed logging for read client

client-spark/common/src/main/java/org/apache/spark/shuffle/RssClientConfig.java, client-spark/common/src/main/java/org/apache/spark/shuffle/RssShuffleUtils.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java, client-spark/spark2/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java, client-spark/spark3/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java, common/src/main/java/com/tencent/rss/common/util/Constants.java, coordinator/src/main/java/com/tencent/rss/coordinator/AccessCandidatesChecker.java, coordinator/src/main/java/com/tencent/rss/coordinator/AccessClusterLoadChecker.java, coordinator/src/main/java/com/tencent/rss/coordinator/AccessManager.java, coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorConf.java, integration-test/common/src/test/java/com/tencent/rss/test/AccessClusterTest.java, integration-test/spark-common/src/test/java/com/tencent/rss/test/SparkSQLWithDelegationShuffleManager.java, integration-test/spark-common/src/test/java/com/tencent/rss/test/SparkSQLWithDelegationShuffleManagerFallback.java, integration-test/spark-common/src/test/resources/candidates, internal-client/src/main/java/com/tencent/rss/client/api/CoordinatorClient.java, internal-client/src/main/java/com/tencent/rss/client/impl/grpc/CoordinatorGrpcClient.java, internal-client/src/main/java/com/tencent/rss/client/request/RssAccessClusterRequest.java, internal-client/src/main/java/com/tencent/rss/client/response/ResponseStatusCode.java, internal-client/src/main/java/com/tencent/rss/client/response/RssAccessClusterResponse.java
- Add a delegation shuffle manager
- choose the actual shuffle manager  (sort or rss)
This pr is related to #61, which add access client.
Yes, client need to config `spark.shuffle.manager` explicitly and add the following config , `spark.rss.accessInfoKey` it specifies which is the config key of the accessInfo and then add the config duration submition.
UT and system test
=> [Feature]Access check in client

bin/start-coordinator.sh, client-spark/spark2/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java, client-spark/spark2/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java, client-spark/spark3/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java, coordinator/pom.xml, coordinator/src/main/java/com/tencent/rss/coordinator/AccessCandidatesChecker.java, coordinator/src/main/java/com/tencent/rss/coordinator/AccessManager.java, coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorConf.java, coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorServer.java, coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorUtils.java, coordinator/src/test/java/com/tencent/rss/coordinator/AccessClusterLoadCheckerTest.java, coordinator/src/test/java/com/tencent/rss/coordinator/AccessManagerTest.java, coordinator/src/test/resources/coordinator.conf, integration-test/common/src/test/java/com/tencent/rss/test/AccessCandidatesCheckerHdfsTest.java
1. Enhance the candidates checker to support hdfs
2. Reset the shuffle manager name on the fly
It is more feasible to support both local and hdfs and we need to reset shuffle manager name the adaptive ESS when fallback to SortShuffleManager, in which the only the sort shuffle manager is supported.
No
UT & system test
=> [Feature] Enhance the DelegationRssShuffleManager to support hdfs conf file and reset the shuffle manager name

client-spark/common/src/main/java/org/apache/spark/shuffle/RssClientConfig.java, client-spark/common/src/main/java/org/apache/spark/shuffle/RssShuffleUtils.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark2/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/test/java/org/apache/spark/shuffle/DelegationRssShuffleManagerTest.java, client/src/main/java/com/tencent/rss/client/api/ShuffleWriteClient.java, client/src/main/java/com/tencent/rss/client/impl/ShuffleWriteClientImpl.java, common/src/main/java/com/tencent/rss/common/util/RssUtils.java, coordinator/src/main/java/com/tencent/rss/coordinator/AccessCandidatesChecker.java, coordinator/src/main/java/com/tencent/rss/coordinator/ClientConfManager.java, coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorConf.java, coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorGrpcService.java, coordinator/src/main/java/com/tencent/rss/coordinator/CoordinatorServer.java, coordinator/src/test/java/com/tencent/rss/coordinator/AccessCandidatesCheckerTest.java, coordinator/src/test/java/com/tencent/rss/coordinator/ClientConfManagerTest.java, coordinator/src/test/resources/coordinator.conf, integration-test/common/src/test/java/com/tencent/rss/test/AccessCandidatesCheckerHdfsTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ClientConfManagerHdfsTest.java, integration-test/common/src/test/java/com/tencent/rss/test/FetchClientConfTest.java, integration-test/spark-common/src/test/java/com/tencent/rss/test/AutoAccessTest.java, integration-test/spark-common/src/test/java/com/tencent/rss/test/DynamicFetchClientConfTest.java, internal-client/src/main/java/com/tencent/rss/client/api/CoordinatorClient.java, internal-client/src/main/java/com/tencent/rss/client/impl/grpc/CoordinatorGrpcClient.java, internal-client/src/main/java/com/tencent/rss/client/request/RssFetchClientConfRequest.java, internal-client/src/main/java/com/tencent/rss/client/response/RssFetchClientConfResponse.java, proto/src/main/proto/Rss.proto
1. Add api to fetch client conf from coordinator
2. Dynamic apply the client conf
Support dynamic update client conf and avoid the requirement to add some client conf other than shuffle manager, client jar.
For now, we only read the conf from local file or hdfs, and we could support db and kv store or leverage a config center in the future.
No
UT & System test
=> [Feature] add the dynamic client conf fetching and updating

README.md, client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/writer/RssShuffleWriter.java, integration-test/spark-common/src/test/java/com/tencent/rss/test/SparkIntegrationTestBase.java, integration-test/spark3/pom.xml, pom.xml
backport 0.2
Support Spark 3.2
We need support more Spark Versions
No
GA passed （include profiles spark2,spark3,spark3.0,spark3.1,spark3.2）
=> [Feature] [0.2] Support Spark 3.2 (#86)

storage/src/main/java/com/tencent/rss/storage/handler/impl/LocalFileWriter.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/LocalFileHandlerTest.java
Modify the method that calculate the offset in the index file.
If we don't have this patch, we run 10TB tpcds, query24a will fail.
When we write many data to dataOutputStream, dataOutputStream.size() won't increase again. dataOutputStream.size() will
always be Integer.MAX_VALUE.
No
Add new uts.
=> [Bugfix] Fix uncorrect index file

storage/src/main/java/com/tencent/rss/storage/handler/impl/LocalFileWriter.java, storage/src/test/java/com/tencent/rss/storage/handler/impl/LocalFileHandlerTest.java
backport 0.3.0
Modify the method that calculate the offset in the index file.
If we don't have this patch, we run 10TB tpcds, query24a will fail.
When we write many data to dataOutputStream, dataOutputStream.size() won't increase again. dataOutputStream.size() will
always be Integer.MAX_VALUE.
No
Add new uts.
Co-authored-by: roryqi <roryqi@tencent.com>
=> [Bugfix] Fix uncorrect index file (#92)

client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/reader/RssShuffleReader.java
When we finish to use RssShuffleDataIterator, we release the RssShuffleDataIterator's memory.
When we use aqe, if there too many partitions, RssShuffleIterator will occupy much memory, the executor will become out of memory.
No
Manually test. Run 10T's tpcds query1 with `spark.sql.adaptive.advisoryPartitionSizeInBytes 256000000`
=> [Bugfix] Exist memory leak when we use aqe

.github/workflows/maven.yml, client-mr/pom.xml, client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java, integration-test/mr/pom.xml, integration-test/mr/src/test/java/org/apache/hadoop/mapreduce/LargeSorterTest.java, integration-test/mr/src/test/java/org/apache/hadoop/mapreduce/MRIntegrationTestBase.java, pom.xml
We add a new AppMaster to support the use of rss. New AppMaster will register shuffles,  get shuffle servers, and send heartbeats.
In real production environments, there are too many MapReduce's jobs. The work is meaningful.
Yes, we bring some new configurations. In another pr, we will update the doc about the use of this feature.
new Uts.
=> [Feature] Firestorm supports MapReduce (Part 1 - AppMaster)

integration-test/common/src/test/java/com/tencent/rss/test/QuorumTest.java
Update timeout setting in QuorumTest.
Without this patch, QuorumTest may issue faked failures due to the tricky timeout setting.
No. 
Previous QuorumTest.
=> [Bugfix] Update QuorumTest to avoid faked failures

client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java, client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client/src/main/java/com/tencent/rss/client/factory/ShuffleClientFactory.java, client/src/main/java/com/tencent/rss/client/impl/ShuffleWriteClientImpl.java, client/src/main/java/com/tencent/rss/client/util/RssClientConfig.java, client/src/test/java/com/tencent/rss/client/impl/ShuffleWriteClientImplTest.java, integration-test/common/src/test/java/com/tencent/rss/test/QuorumTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleServerGrpcTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleWithRssClientTest.java
Write client send blocks in two rounds.
In the primary round, we only send [0, replicaWrite) data.
In the secondary round, we send [replicaWrite, replica) data.
When  the primary round is totally successful, the secondary round can be skipped. 
Without this patch, the  quorum writer will send whole replica times of blocks even all RPCs are successful.
No.
All previous UTs and new UTs.
=> [Improvement] Optimize quorum write by skipping unnecessary blocks

client-mr/pom.xml
Include lz4 jar in our shade jar
If we don't have this patch, we will encounter exception that we can't load Lz4 class.
No
Manual test
=> [Bugfix] Shade jar should contain lz4 jar

common/src/main/java/com/tencent/rss/common/util/RssUtils.java
Filter the interface address that don't have broadcast address
Some machines have multiple interface address, but some interface address don't have broadcast address, we can't use it to communicate, so we should filter it.
No
Manual Test
=> [Improvement]  Filter the interface address that don't have broadcast address

.github/workflows/maven.yml
Parallelize github workflow to speed up CI.
Reduced wall-clock time of CI from ~1 hour to ~25 minutes.
No.
https://github.com/kaijchen/Firestorm/actions/runs/2362806351
=> [Improvement] Parallelize github workflow to speed up CI

client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/RssMRUtilsTest.java, client-spark/common/src/test/java/org/apache/spark/shuffle/writer/WriteBufferManagerTest.java, client/src/test/java/com/tencent/rss/client/ClientUtilsTest.java, common/src/main/java/com/tencent/rss/common/util/Constants.java
Rss TaskAttemptId length is 20, we should guarantee the map task id length is less than that value. And we adjust the length of task to run more tasks.
If we don't have this patch,  task cannot retry succesfully. Task will throw exception
Can't support taskAttemptId[4294976976], the max value should be 1048575
at com.tencent.rss.client.util.ClientUtils.getBlockId(ClientUtils.java:43)
at org.apache.hadoop.mapred.SortWriteBufferManager.createShuffleBlock(SortWriteBufferManager.java:292)
No
Add new UT
=> [Bugfix] Fix taskAttemptId length error

client-spark/spark3/src/main/java/org/apache/spark/shuffle/DelegationRssShuffleManager.java
Use reflection to support Delegated ShuffleManager for Spark3.1/3.0 and Rss
Without this patch, `mvn package -Pspark3.0` will fail. 
No
Manually run `mvn package -Pspark3.0`
=> [Bugfix] Support Delegated ShuffleManager for Spark3.1/3.0 and Rss

client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkShuffleUtils.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, common/src/main/java/com/tencent/rss/common/RemoteStorageInfo.java, coordinator/src/main/java/com/tencent/rss/coordinator/ApplicationManager.java, integration-test/spark2/src/test/java/com/tencent/rss/test/GetReaderTest.java, integration-test/spark3/src/test/java/com/tencent/rss/test/GetReaderTest.java
Executor get remote storage info from RssShuffleHadle.
The driver's ShuffleManager register shuffle and fetch the remote storage and put then in the RssShuffleHandle. The remote storage in executor's ShuffleManager is useless and the task should get remote storage from RssShuffleHandle when it get reader.
No
Normal  ut and system test
=> [Bugfix] executor should get remote storage from ShuffleHandle

client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssFetcher.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/EvenFetcherTest.java
MR Reduce should only fetch one attempt of each map task.
Without this PR, the Reduce will assume to accept all attempt of each map task and fail in taskID check.
No.
By hand.
=> [Bugfix] MR Reduce should only fetch one attempt of each map task

client-mr/src/main/java/org/apache/hadoop/mapred/RssMapOutputCollector.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssEventFetcher.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssShuffle.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/RssMRUtilsTest.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/EvenFetcherTest.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMasterTest.java, integration-test/mr/src/test/java/com/tencent/rss/test/FailoverAppMaster.java, integration-test/mr/src/test/java/com/tencent/rss/test/LargeSorterTest.java, integration-test/mr/src/test/java/com/tencent/rss/test/MRIntegrationTestBase.java
We increase a extra configuration to store rss configuration information, we don't modify the job.xml on the HDFS any more.
If we don't have this patch, mr application cannot re-execute successfully. We will encounter the exception
No
new UT
=> [Improvement] Supports MR application  re-execute

client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/MRIdHelper.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssShuffle.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/RssMRUtilsTest.java, client-spark/common/src/test/java/org/apache/spark/shuffle/reader/RssShuffleDataIteratorTest.java, client/src/main/java/com/tencent/rss/client/factory/ShuffleClientFactory.java, client/src/main/java/com/tencent/rss/client/impl/ShuffleReadClientImpl.java, client/src/main/java/com/tencent/rss/client/request/CreateShuffleReadClientRequest.java, client/src/main/java/com/tencent/rss/client/util/DefaultIdHelper.java, client/src/main/java/com/tencent/rss/client/util/IdHelper.java, client/src/test/java/com/tencent/rss/client/impl/ShuffleReadClientImplTest.java, integration-test/common/src/test/java/com/tencent/rss/test/DiskErrorToleranceTest.java, integration-test/common/src/test/java/com/tencent/rss/test/MultiStorageFaultToleranceTest.java, integration-test/common/src/test/java/com/tencent/rss/test/MultiStorageTest.java, integration-test/common/src/test/java/com/tencent/rss/test/QuorumTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleServerWithHdfsTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleWithRssClientTest.java, integration-test/spark-common/src/test/java/com/tencent/rss/test/SparkClientWithLocalTest.java
We use high bits to express task attempt times, task attempt times don't vary frequently. So we should not increase memory of bitmap.
In our production environment, task often will be preempted. Four times is not enough, so we increase max attempts to  64.
No
Exist UT and manual test
=> [Improvement] Optimize taskAttemptId format in MR application

client-mr/src/main/java/org/apache/hadoop/mapreduce/task/reduce/RssBypassWriter.java, client-mr/src/test/java/org/apache/hadoop/mapreduce/task/reduce/FetcherTest.java
In InMemoryMapOutput constructor method, we create a decompressor or borrow a decompressor from pool. Now we need to put it back, otherwise we will create a decompressor for every InMemoryMapOutput object, they will cause `out of direct memory` problems.
If we don't have this patch, some applications will fail because of oom.
No
New ut
=> [Improvement] Reuse the codec from a pool

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
Only initialize the heartbeat thread pool when the role is driver
Just to avoid creating extra thread pool.
No
No
=> [Improvement] Only initialize the heartbeat thread pool when the role is driver

client-mr/src/main/java/org/apache/hadoop/mapred/SortWriteBufferManager.java, internal-client/src/main/java/com/tencent/rss/client/impl/grpc/ShuffleServerGrpcClient.java
Add rpc timeout for   `requireBuffer` method
Some tasks hang for long time, and task is blocked by `requreBuffer` method, jstack is below as
No
Manual test
=> [Improvement]  Add rpc timeout for   `requireBuffer` method

client-spark/common/src/main/java/org/apache/spark/shuffle/writer/WriteBufferManager.java
The problem only occurs when `wb.getMemoryUsed() > bufferSize` and `usedBytes.get() - inSendListBytes.get() > spillSize`. 
Although it doesn't seem to happen because of the logic, i think it should be optimized by using `addAll` to avoid confusion.
Better code
No
No need.
=> [Minor] Prevent returning incomplete shuffle blocks

client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRConfig.java, client-mr/src/main/java/org/apache/hadoop/mapreduce/RssMRUtils.java, client-spark/common/src/main/java/org/apache/spark/shuffle/RssSparkConfig.java, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client-spark/spark3/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java, client/src/main/java/com/tencent/rss/client/factory/ShuffleClientFactory.java, client/src/main/java/com/tencent/rss/client/impl/ShuffleWriteClientImpl.java, client/src/main/java/com/tencent/rss/client/util/RssClientConfig.java, client/src/test/java/com/tencent/rss/client/impl/ShuffleWriteClientImplTest.java, integration-test/common/src/test/java/com/tencent/rss/test/QuorumTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleServerGrpcTest.java, integration-test/common/src/test/java/com/tencent/rss/test/ShuffleWithRssClientTest.java
As we know that parallelStream will use the default forkjoin pool in entire jvm. To avoid it, use the custom pool and allow to specify the pool size.
use separate forkjoin pool to send shuffle data
Yes, introduce the configuration to control the size of forkjoinpool.
mapreduce.rss.client.data.transfer.pool.size for MapReduce
spark.rss.client.data.transfer.pool.size for Spark
GA passed.
=> Avoid using the default forkjoin pool by parallelStream directly

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
backport 0.5.0
We need to judge heartbeatExecutorService whether is null when we will stop it.
#177 pr introduce this problem, when we run Spark applications on our cluster, the executor will throw NPE when method `stop` is called.
No
Manual test
=> [Bugfix] [0.5.0] Fix spark2 executor stop NPE problem

client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
We need to judge heartbeatExecutorService whether is null when we will stop it.
#177 pr introduce this problem, when we run Spark applications on our cluster, the executor will throw NPE when method `stop` is called.
No
Manual test
=> [Bugfix] Fix spark2 executor stop NPE problem

client-mr/src/main/java/org/apache/hadoop/mapreduce/v2/app/RssMRAppMaster.java
backport 0.5.0
We should acquire the storageType from extraConf. 
If we don't have this patch, MR don't work when we use dynamic conf and MEMORY_LOCALE_HDFS storageType.
No
Manual test
=> [Bugfix] [0.5] Fix MR don't have remote storage information when we use dynamic conf and MEMORY_LOCALE_HDFS storageType

README.md, client-spark/spark2/src/main/java/org/apache/spark/shuffle/RssShuffleManager.java
1. Add checking of spark.sql.adaptive.enabled=false in RssShuffleManager's constructor for spark2.
2. Add a description of this parameter in the Deploy Spark Client section of the readme.
When use firestorm+spark2+spark.sql.adaptive.enabled=true，the result is wrong，but we didn't get any hints.
No
Manual test
=> Check ADAPTIVE_EXECUTION_ENABLED in RssShuffleManager

README.md, spark-patches/spark-3.2.1_dynamic_allocation_support.patch
Add the dynamic allocation patch for Spark 3.2, solve issue #106
If we don't have this patch, users can't use dynamic allocation in Spark 3.2.
No
Manual test
=> [Improvement] Add dynamic allocation patch for Spark 3.2

.gitignore, README.md, build_distribution.sh, pom.xml
- Add `--spark2-mvn`, `--spark3-mvn` parameters in `build_distribution.sh` to support compiling different profiles, we can pass in different maven parameters, such as profile, spark version.
- Add `--help` parameters in `build_distribution.sh`, fix typo.
- gitignore ignores the tar package generated by build.
- README added how to use `build_distribution.sh`.
If we use such a command to build, Spark2 will also use the Spark3 version to compile, so we'd better distinguish the build options of different versions.
```bash
./build_distribution.sh -Pspark3.2
```
No
local test
=> Support build_distribution.sh to specify different mvn build options for Spark2 and Spark3

README.md, docs/client_guide.md, docs/coordinator_guide.md, docs/index.md, docs/pageA.md, docs/server_guide.md
1.  Put detailed configuration to doc subdirectory.
2. Add doc for client quorum setting.
Update doc
No.
Just doc.
=> [Improvement] Move detailed client configuration to individual doc

common/src/main/java/com/tencent/rss/common/util/RssUtils.java, common/src/test/java/com/tencent/rss/common/util/RssUtilsTest.java
Method `getHostIp` can acquire IP by environment variable.
For K8S, there are too many IPs, it's hard to decide which we should use. So we use the environment variable to tell RSS
to use which one.
NO
UT
=> [Improvement] Add RSS_IP environment variable support for K8S
